{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Exception Handling \n",
    "\n",
    "This notebook is intended to demonstrate the basics of exception handling and the use of context management in order to handle standard cases. I'm hoping that notes can be live and editable to create a set of documentation for you to use as you're learning Python. \n",
    "\n",
    "## Exceptions \n",
    "\n",
    "**Exceptions** are a tool that programmers use to describe errors or faults that are _fatal_ to the program; e.g. the program cannot or should not continue when an exception occurs. Exceptions can occur due to programming errors, user errors, or simply unexpected conditions like no internet access. Exceptions themselves are simply objects that contain information about what went wrong. Exceptions are usually defined by their `type` - which describes broadly the class of exception that occurred, and by a `message` that says specifically what happened. Here are a few common exception types:\n",
    "\n",
    "- `SyntaxError`: raised when the programmer has made a mistake typing Python code correctly. \n",
    "- `AttributeError`: attempting to access an attribute on an object that does not exist \n",
    "- `KeyError`: attempting to access a key in a dictionary that does not exist \n",
    "- `TypeError`: raised when an argument to a function is not the right type (e.g. a `str` instead of `int`) \n",
    "- `ValueError`: when an argument to a function is the right type but not in the right domain (e.g. an empty string)\n",
    "- `ImportError`: raised when an import fails \n",
    "- `IOError`: raised when Python cannot access a file correctly on disk \n",
    "\n",
    "Exceptions are defined in a class hierarchy - e.g. every exception is an object whose class defines it's type. The base class is the `Exception` object. All `Exception` objects are initialized with a message - a string that describes exactly what went wrong. Constructed objects can then be \"raised\" or \"thrown\" with the `raise` keyword:\n",
    "\n",
    "```python\n",
    "raise Exception(\"Something bad happened!\") \n",
    "```\n",
    "\n",
    "The reason the keyword is `raise` is because Python program execution creates what's called a \"stack\" as functions call other functions, which call other functions, etc. When a function (at the bottom of the stack) raises an Exception, it is propagated up through the call stack so that every function gets a chance to \"handle\" the exception (more on that later). If the exception reaches the top of the stack, then the program terminates and a _traceback_ is printed to the console. The traceback is meant to help developers identify what went wrong in their code. \n",
    "\n",
    "Let's take a look at a simple example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def first(step, badstep=None):\n",
    "    # Increment the step \n",
    "    step += 1 \n",
    "    \n",
    "    # Check if this is a bad step \n",
    "    if badstep == step:\n",
    "        raise ValueError(\"Failed after {} steps\".format(step))\n",
    "    \n",
    "    # Call sub steps in order \n",
    "    step = first_task_one(step, badstep)\n",
    "    step = first_task_two(step, badstep)\n",
    "    \n",
    "    # Return the step that we're on \n",
    "    return step \n",
    "\n",
    "\n",
    "def first_task_one(step, badstep=None):\n",
    "    # Increment the step \n",
    "    step += 1 \n",
    "    \n",
    "    # Check if this is a bad step \n",
    "    if badstep == step:\n",
    "        raise ValueError(\"Failed after {} steps\".format(step))\n",
    "    \n",
    "    # Call sub steps in order \n",
    "    step = first_task_one_subtask_one(step, badstep)\n",
    "    \n",
    "    # Return the step that we're on \n",
    "    return step \n",
    "\n",
    "\n",
    "def first_task_one_subtask_one(step, badstep=None):\n",
    "    # Increment the step \n",
    "    step += 1 \n",
    "    \n",
    "    # Check if this is a bad step \n",
    "    if badstep == step:\n",
    "        raise ValueError(\"Failed after {} steps\".format(step))\n",
    "    \n",
    "    # Return the step that we're on \n",
    "    return step \n",
    "\n",
    "\n",
    "def first_task_two(step, badstep=None):\n",
    "    # Increment the step \n",
    "    step += 1 \n",
    "    \n",
    "    # Check if this is a bad step \n",
    "    if badstep == step:\n",
    "        raise ValueError(\"Failed after {} steps\".format(step))\n",
    "    \n",
    "    # Return the step that we're on \n",
    "    return step \n",
    "\n",
    "\n",
    "def second(step, badstep=None):\n",
    "    # Increment the step \n",
    "    step += 1 \n",
    "    \n",
    "    # Check if this is a bad step \n",
    "    if badstep == step:\n",
    "        raise ValueError(\"Failed after {} steps\".format(step))\n",
    "    \n",
    "    # Call sub steps in order \n",
    "    step = second_task_one(step, badstep)\n",
    "    \n",
    "    # Return the step that we're on \n",
    "    return step \n",
    "\n",
    "\n",
    "def second_task_one(step, badstep=None):\n",
    "    # Increment the step \n",
    "    step += 1 \n",
    "    \n",
    "    # Check if this is a bad step \n",
    "    if badstep == step:\n",
    "        raise ValueError(\"Failed after {} steps\".format(step))\n",
    "    \n",
    "    # Return the step that we're on \n",
    "    return step \n",
    "\n",
    "def main(badstep=None, **kwargs):\n",
    "    \"\"\"\n",
    "    This function is the entry point of the program, it does \n",
    "    work on the arguments by calling each step function, which \n",
    "    in turn call substep functions. \n",
    "    \n",
    "    Passing in a number for badstep will cause whichever step \n",
    "    that is to raise an exception. \n",
    "    \"\"\"\n",
    "    \n",
    "    step = 0 # count the steps \n",
    "    \n",
    "    # Execute each step one at a time. \n",
    "    step = first(step, badstep) \n",
    "    step = second(step, badstep)\n",
    "    \n",
    "    # Return a report \n",
    "    return \"Sucessfully executed {} steps\".format(step) \n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The above example represents a fairly complex piece of code that has lots of functions that call lots of other functions. The question is then, _how do we know where our code went wrong?_ The answer is the _traceback_ - which deliniates exactly the functions that the exception was raised through. Let's trigger the exception and the traceback:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Failed after 3 steps",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-5-e46a77400742>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-4-f90d7e96381d>\u001b[0m in \u001b[0;36mmain\u001b[0;34m(badstep, **kwargs)\u001b[0m\n\u001b[1;32m     93\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     94\u001b[0m     \u001b[0;31m# Execute each step one at a time.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 95\u001b[0;31m     \u001b[0mstep\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfirst\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbadstep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     96\u001b[0m     \u001b[0mstep\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msecond\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbadstep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     97\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-4-f90d7e96381d>\u001b[0m in \u001b[0;36mfirst\u001b[0;34m(step, badstep)\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      9\u001b[0m     \u001b[0;31m# Call sub steps in order\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 10\u001b[0;31m     \u001b[0mstep\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfirst_task_one\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbadstep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     11\u001b[0m     \u001b[0mstep\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfirst_task_two\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbadstep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-4-f90d7e96381d>\u001b[0m in \u001b[0;36mfirst_task_one\u001b[0;34m(step, badstep)\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     25\u001b[0m     \u001b[0;31m# Call sub steps in order\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 26\u001b[0;31m     \u001b[0mstep\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfirst_task_one_subtask_one\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbadstep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     27\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     28\u001b[0m     \u001b[0;31m# Return the step that we're on\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-4-f90d7e96381d>\u001b[0m in \u001b[0;36mfirst_task_one_subtask_one\u001b[0;34m(step, badstep)\u001b[0m\n\u001b[1;32m     36\u001b[0m     \u001b[0;31m# Check if this is a bad step\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     37\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mbadstep\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mstep\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 38\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Failed after {} steps\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     39\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     40\u001b[0m     \u001b[0;31m# Return the step that we're on\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: Failed after 3 steps"
     ]
    }
   ],
   "source": [
    "main(3)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The way to read the traceback is to start at the very bottom. As you can see it indicates the type of the exception, followed by a colon, and then the message that was passed to the exception constructor. Often, this information is enough to figure out what is going wrong. However, if we're unsure where the problem occurred, we can step back through the traceback in a bottom to top fashion. \n",
    "\n",
    "The first part of the traceback indicates the exact line of code and file where the exception was raised, as well as the name of the function it was raised in. If you called `main(3)` than this indicates that `first_task_one_subtask_one` is the function where the problem occurred. If you wrote this function, then perhaps that is the place to change your code to handle the exception. \n",
    "\n",
    "However, many times you're using third party libraries or Python standard library modules, meaning the location of the exception raised is not helpful, since you can't change that code. Therefore, you will continue up the call stack until you discover a file/function in the code you wrote. This will provide the surrounding context for why the error was raised, and you can use `pdb` or even just `print` statements to debug the variables around that line of code. Alternatively you can simply handle the exception, which we'll discuss shortly. In the example above, we can see that `first_task_one_subtask_one` was called by `first_task_one` at line 46, which was called by `first` at line 30, which was called by `main` at line 14. \n",
    "\n",
    "## Catching Exceptions \n",
    "\n",
    "If the exception was caused by a programming error, the developer can simply change the code to make it correct. However, if the exception was created by bad user input or by a bad environmental condition (e.g. the wireless is down), then you don't want to crash the program. Instead you want to provide feedback and allow the user to fix the problem or try again. Therefore in your code, you can catch exceptions at the place they occur using the following syntax:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # Code that may raise an exception \n",
    "except AttributeError as e:\n",
    "    # Code to handle the exception case\n",
    "finally:\n",
    "    # Code that must run even if there was an exception \n",
    "```\n",
    "\n",
    "What we're basically saying is `try` to do the code in the first block - hopefully it works. If it raises an `AttributeError` save that exception in a variable called `e` (the `as e` syntax) then we will deal with that exception in the `except` block. Then `finally` run the code in the `finally` block even if an exception occurs. By specifying exactly the type of exception we want to catch (`AttributeError` in this case), we will not catch all exceptions, only those that are of the type specified, including subclasses. If we want to catch _all_ exceptions, you can use one of the following syntaxes:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # Code that may raise an exception \n",
    "except:\n",
    "    # Except all exceptions \n",
    "```\n",
    "\n",
    "or \n",
    "\n",
    "```python\n",
    "try:\n",
    "    # Code that may raise an exception \n",
    "except Exception as e:\n",
    "    # Except all exceptions and capture in variable e \n",
    "```\n",
    "\n",
    "However, it is best practice to capture _only_ the type of exception you expect to happen, because you could accidentaly create the situation where you're capturing fatal errors but not handling them appropriately. Here is an example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No error occurred!\n",
      "This runs no matter what!\n"
     ]
    }
   ],
   "source": [
    "import random \n",
    "\n",
    "class RandomError(Exception):\n",
    "    \"\"\"\n",
    "    A custom exception for this code block. \n",
    "    \"\"\"\n",
    "    pass \n",
    "\n",
    "\n",
    "def randomly_errors(p_error=0.5):\n",
    "    if random.random() <= p_error:\n",
    "        raise RandomError(\"Error raised with {:0.2f} likelihood!\".format(p_error))\n",
    "\n",
    "\n",
    "try:\n",
    "    randomly_errors(0.5) \n",
    "    print(\"No error occurred!\")\n",
    "except RandomError as e:\n",
    "    print(e)\n",
    "finally:\n",
    "    print(\"This runs no matter what!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This code snippet demonstrates a couple of things. First you can define your own, program-specific exceptions by defining a class that extends `Exception`. We have done so and created our own `RandomError` exception class. Next we have a function that raises a `RandomError` with some likelihood which is an argument to the function. Then we have our exception handling block that calls the function and handles it. \n",
    "\n",
    "Try the following the code snippet:\n",
    "\n",
    "- Change the likelihood of the error to see what happens \n",
    "- except `Exception` instead of `RandomError`\n",
    "- except `TypeError` instead of `RandomError` \n",
    "- Call `randomly_errors` again inside of the `except` block \n",
    "- Call `randomly_errors` again inside of the `finally` block\n",
    "\n",
    "Make sure you run the code multiple times since the error does occur randomly! \n",
    "\n",
    "## LBYL vs. EAFP \n",
    "\n",
    "One quick note on exception handling in Python. You may wonder why you must use a `try/except` block to handle exceptions, couldn't you simply do a check that the exception won't occur before it does? For example, consider the following code:\n",
    "\n",
    "```python\n",
    "if key in mydict:\n",
    "    val = mydict[key] \n",
    "    # Do something with val \n",
    "else:\n",
    "    # Handle the fact that mydict doesn't have a required key. \n",
    "```\n",
    "\n",
    "This code checks if a key exists in the dictionary before using it, then uses an else block to handle the \"exception\". This is an alternative to the following code:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    val = mydict[key]\n",
    "    # Do something with val \n",
    "except KeyError:\n",
    "    # Handle the fact that mydict doesn't have a required key. \n",
    "```\n",
    "\n",
    "Both blocks of code are valid. In fact they have names:\n",
    "\n",
    "1. Look Before You Leap (LBYL)\n",
    "2. Easier to Ask Forgiveness than Permission (EAFP) \n",
    "\n",
    "For a variety of reasons, the second example (EAFP) is more _pythonic_ &mdash; that is the prefered Python Syntax, commonly accepted by Python developers. For more on this, please see Alex Martelli's excellent PyCon 2016 talk, [Exception and error handling in Python 2 and Python 3](https://www.youtube.com/watch?v=frZrBgWHJdY). \n",
    "\n",
    "## Context Management \n",
    "\n",
    "Python does provide a syntax for embedding common `try/except/finally` blocks in an easy to read format called context management. To motivate the example, consider the following code snippet:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    fobj = open('path/to/file.txt, 'r') \n",
    "    data = fobj.read() \n",
    "except FileNotFoundError as e:\n",
    "    print(e)\n",
    "    print(\"Could not find the necessary file!) \n",
    "finally:\n",
    "    fobj.close() \n",
    "```\n",
    "\n",
    "This is a very common piece of code that opens a file and reads data from it. If the file doesn't exist, we simply alert the user that the required file is missing. No matter what, the file is closed. This is critical because if the file is not closed properly, it can be corrupted or not available to other parts of the program. Data loss is not acceptable, so we need to ensure that no matter what the file is closed when we're done with it. So we can do the following:\n",
    "\n",
    "```python\n",
    "with open('path/to/file.txt', 'r') as fobj:\n",
    "    data = fobj.read() \n",
    "```\n",
    "\n",
    "The `with as` syntax implements context management. On `with`, a function called the `enter` function is called to do some work on behalf of the user (in this case open a file), and the return of that function is saved in the `fobj` variable. When this block is complete, the finally is called by implementing an `exit` function. (Note that the `except` part is not implemented in this particular code). In this way, we can ensure that the `try/finally` for opening and reading files is correctly implemented. \n",
    "\n",
    "Writing your own context managers is possible, but beyond the scope of this note. Suffice it to say, you should always use the `with/as` syntax for opening files!"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
